export interface Project {
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  year: string;
  featured?: boolean;
  widget: string;
  desc: string;
  role: string;
  timeline: string;
  tech: string[];
  features?: string[];
  metrics?: [string, string][];
  link?: string;
  github?: string;
}

export const PROJECTS: Project[] = [
  {
    slug: 'fairlint-dl',
    title: 'FairLint DL',
    subtitle: 'Deep-learning fairness debugger shipped as a VS Code extension',
    category: 'AI/ML · Open Source',
    year: '2026',
    widget: 'fairlintDl',
    desc: 'A deep-learning-based fairness debugger that ships as a VS Code extension. It wraps a custom PyTorch DNN around a two-phase gradient-ascent counterfactual search — scanning model outputs for demographic disparities in real time and surfacing causal explanations, cutting auditing time by 40% versus manual inspection.',
    role: 'Sole engineer',
    timeline: '2025 — 2026',
    tech: ['PyTorch', 'VS Code API', 'TypeScript', 'Causal DAGs', 'Gradient Ascent', 'Counterfactuals', 'Node.js'],
    features: [
      'Real-time fairness scanning integrated into the VS Code sidebar',
      'Two-phase gradient-ascent counterfactual search to isolate causal bias sources',
      'Custom PyTorch DNN for demographic disparity detection across 12 fairness metrics',
      'Interactive highlight layer — flagged rows glow directly in the editor',
      '40% reduction in auditing time vs. standalone script-based workflows',
    ],
    metrics: [
      ['auditing time', '−40%'],
      ['fairness metrics', '12 supported'],
      ['counterfactual samples', '2,048 / run'],
    ],
  },
  {
    slug: 'galaxy-morphology-xai',
    title: 'Galaxy Morphology XAI',
    subtitle: 'Systematic evaluation of post-hoc explainability across four CNN architectures',
    category: 'Research · AI/ML',
    year: '2026',
    featured: true,
    widget: 'galaxyXai',
    desc: 'Deep learning classifiers are now standard tools for automated galaxy morphology analysis at the scale of next-generation astronomical surveys like Rubin LSST. However, black-box neural networks present a critical trust problem for scientific use — astronomers cannot verify whether predictions rely on genuine morphological features or spurious correlations. This project conducts a systematic evaluation of four post-hoc explainability methods (Grad-CAM, LIME, Integrated Gradients, GradientSHAP) across four CNN architectures on two galaxy morphology datasets, using quantitative faithfulness metrics to show that no single explanation method dominates universally.',
    role: 'Sole researcher',
    timeline: 'Jan 2025 — May 2025',
    tech: ['PyTorch', 'Captum', 'LIME', 'Grad-CAM', 'Python', 'NumPy', 'Matplotlib', 'scikit-learn'],
    features: [
      'Systematic evaluation of Grad-CAM, LIME, Integrated Gradients, and GradientSHAP across ResNet-18, VGG-16, EfficientNet-B0, and Custom CNN',
      'Quantitative faithfulness metrics: Deletion AUC, Insertion AUC, Consistency, and Sparsity',
      'Cross-dataset stress test on Galaxy Zoo Evo to validate explainability generalization',
      'Statistical significance via Wilcoxon signed-rank and McNemar tests',
      'Per-class analysis revealing Featured galaxies receive 33% lower Deletion AUC than Smooth galaxies',
    ],
    metrics: [
      ['best accuracy', '96.1% (ResNet-18)'],
      ['datasets', 'Galaxy10 DECaLS + Galaxy Zoo Evo'],
      ['images', '9,060 + 1,698'],
      ['best Deletion AUC', '0.32 (Grad-CAM)'],
      ['best Insertion AUC', '0.89 (GradientSHAP)'],
      ['best Consistency', '≥ 0.96 (Grad-CAM)'],
    ],
    github: 'https://github.com/Archit1706/galaxy-morphology-xai',
  },
  {
    slug: 'osm-temporary-road-closures',
    title: 'OSM Temporary Road Closures',
    subtitle: 'Database & API for the OpenStreetMap Foundation · GSoC 2025',
    category: 'Full Stack · OSS',
    year: '2025',
    featured: true,
    widget: 'osmMap',
    desc: 'A full-stack, AGPL-licensed platform built during Google Summer of Code 2025 for the OpenStreetMap Foundation. Community users submit closures via a Next.js/Leaflet interface, while a FastAPI service backed by PostgreSQL + PostGIS validates, stores, and serves geospatial data. Locations are encoded with OpenLR to remain map-provider-agnostic, and a Valhalla integration powers closure-aware routing across auto, bicycle, and pedestrian modes.',
    role: 'Lead engineer · GSoC contributor',
    timeline: 'May 2025 — Aug 2025',
    tech: ['Next.js', 'TypeScript', 'Leaflet', 'Tailwind', 'FastAPI', 'PostgreSQL/PostGIS', 'Redis', 'OpenLR', 'Valhalla', 'Docker', 'Nginx'],
    features: ['Responsive UI', 'Geospatial Data Handling', 'Closure-Aware Routing', 'OAuth2/JWT Authentication', 'Rate Limiting', 'Containerized Deployment'],
    metrics: [['locations', '12k+'], ['routes/day', '3.2k'], ['p99 latency', '94ms']],
    link: 'https://closures.osm.ch/',
    github: 'https://github.com/Archit1706/temporary-road-closures',
  },
  {
    slug: 'keya-ai',
    title: 'Keya AI',
    subtitle: 'Agentic AI Assistant for Real Estate',
    category: 'AI Agents · Web',
    year: '2025',
    featured: true,
    widget: 'chatAgent',
    desc: 'An advanced AI assistant streamlining the real estate process for both agents and buyers. Built on LangChain, Azure OpenAI, and Vector Databases — Keya offers personalized property recommendations, transit information, and dual chat interfaces (agent-side and property-specific).',
    role: 'Full-stack engineer',
    timeline: '2025',
    tech: ['Next.js', 'Tailwind', 'Flask', 'LangChain', 'Azure OpenAI', 'SerpAPI', 'Zillow/RapidAPI', 'GreatSchools', 'Cloudflare R2', 'i18n'],
    features: ['Personalized Property Recommendations', 'Transit Information', 'Agent Chat', 'Property-Specific Chat Interfaces'],
    metrics: [['agent tools', '8'], ['langs', '4'], ['avg ttfb', '320ms']],
    link: 'https://keya-ai.vercel.app/',
    github: 'https://github.com/Archit1706/Keya-Agentic-AI-assistant-for-Real-Estate',
  },
  {
    slug: 'fairlend-miners',
    title: 'FairLend Miners',
    subtitle: 'Racial & gender disparity investigation in U.S. mortgage lending · HMDA 2023',
    category: 'Research · Data Mining',
    year: '2026',
    widget: 'fairLend',
    desc: 'A data mining investigation into racial and gender disparities in U.S. mortgage lending. Using 103,481 cleaned mortgage applications from the HMDA 2023 dataset, I built a PySpark pipeline that loads a 4 GB national file, filters to Chicago, and implements both standard equal-frequency binning and the epsilon-biased fair binning algorithm from research by Asudeh et al. The project uncovers that routine preprocessing steps—like binning income—can silently amplify existing racial bias by up to 9.63 percentage points.',
    role: 'Lead data engineer',
    timeline: 'Spring 2025',
    tech: ['PySpark', 'Python', 'HMDA 2023', 'FP-Growth', 'K-Means', 'Parquet', 'Pandas', 'Matplotlib', 'scikit-learn'],
    features: [
      'PySpark pipeline processing 4 GB HMDA 2023 national dataset, filtered to 103,481 Chicago applications',
      'Implemented epsilon-biased fair binning (Asudeh et al.) alongside standard equal-frequency binning',
      'Measured maximum demographic deviation across all bins: standard 9.63% vs fair binning 8.00%',
      'FP-Growth association rule mining: high DTI ratio → denial at 67.2% confidence, 2.81 lift',
      'K-Means clustering audit flagging 10 cases of disparate impact under the four-fifths legal rule',
      'Exported 3 Parquet files (300K+ records) enabling downstream team analyses',
    ],
    metrics: [
      ['applications', '103,481'],
      ['dataset size', '4 GB'],
      ['standard binning bias', '9.63%'],
      ['fair binning bias', '8.00%'],
      ['price of fairness', '29.4%'],
      ['disparate impact cases', '10 flagged'],
      ['FP-Growth confidence', '67.2% (DTI → denial)'],
    ],
    github: 'https://github.com/Archit1706/FairLend-Miners',
  },
  {
    slug: 'green-pipe',
    title: 'GreenPipe',
    subtitle: 'First GitLab Duo Agent implementing GSF carbon-aware CI/CD scheduling',
    category: 'AI Agents · Green Software',
    year: '2026',
    widget: 'greenPipe',
    desc: 'A GitLab Duo Agent that measures the carbon footprint of every CI/CD pipeline using the GSF Software Carbon Intensity (SCI) standard — ISO/IEC 21031:2024. It classifies pipeline urgency from commit messages via a fine-tuned INT8-quantized DistilBERT model, autonomously reschedules deferrable pipelines to low-carbon windows, profiles code for energy inefficiencies using Anthropic Claude, and gamifies sustainability with a contributor carbon leaderboard. GreenPipe applies the same optimisations it recommends: its own SCI score is ~0.00079 gCO₂e per pipeline analysis.',
    role: 'Sole engineer · Hackathon project',
    timeline: '2025',
    tech: ['Python', 'FastAPI', 'DistilBERT', 'Anthropic Claude', 'GSF Carbon Aware SDK', 'GSF Impact Framework', 'PostgreSQL', 'Docker', 'Railway'],
    features: [
      'SCI carbon measurement per pipeline using ISO/IEC 21031:2024 formula: SCI = ((E × I) + M) / R',
      'DistilBERT NLP urgency classifier (INT8 quantized, 58% less energy than FP32)',
      '3 auto-deferral modes: recommend-only, approval-required, auto-execute',
      'Multi-region carbon comparison across 5 cloud regions to find greenest runner',
      'Anthropic Claude code profiler for energy inefficiency detection',
      'Contributor carbon leaderboard and automated GitLab MR comment reports',
    ],
    metrics: [
      ['tests passing', '299'],
      ['own SCI score', '~0.00079 gCO₂e / pipeline'],
      ['cache reduction', '97% fewer SDK calls'],
      ['NLP energy savings', '58% vs FP32'],
      ['deferral modes', '3 (safe)'],
    ],
    link: 'https://green-pipe.up.railway.app/docs',
    github: 'https://github.com/Archit1706/green-pipe',
  },
  {
    slug: 'optimal-congestion-zone-analysis',
    title: 'Optimal Congestion Zone Analysis',
    subtitle: 'Computational urban analytics framework · UIC',
    category: 'Urban Analytics',
    year: '2025',
    featured: true,
    widget: 'cycleGraph',
    desc: 'A computational urban analytics framework for determining optimal congestion pricing zone boundaries. Integrates OpenStreetMap road network data, census tract geometries, and origin-destination trip flows. Leverages graph theory (NetworkX), geospatial analysis (GeoPandas, Shapely), and transportation data processing to evaluate candidate boundaries based on trip coverage, monitoring requirements, and spatial efficiency.',
    role: 'Research assistant',
    timeline: 'Feb 2025 — May 2025',
    tech: ['Python', 'OSMnx', 'NetworkX', 'GeoPandas', 'Shapely', 'Matplotlib', 'Pandas', 'NumPy'],
    features: ['Automated Boundary Detection', 'Geospatial Trip Flow Analysis', 'Cut Edge Optimization', 'Quantitative Evaluation Metrics', 'Modular Pipeline Architecture', 'Scalable Multi-City Framework'],
    metrics: [['nodes', '38k'], ['cycles tested', '472'], ['cut-edges/run', '~120']],
    link: 'https://docs.google.com/document/d/1qDFizGekW9mCApi7k8pXx-rC9qcEInEFzZWHhMpDN7Y/',
    github: 'https://github.com/Archit1706/optimal-cordon-zones',
  },
  {
    slug: 'real-estate-360',
    title: 'RealEstate 360',
    subtitle: 'Immersive AR/VR house-hunting platform',
    category: 'Full Stack · AR/VR',
    year: '2024',
    featured: true,
    widget: 'panorama',
    desc: 'The future of online house-hunting — leveraging Augmented Reality, Virtual Reality, and AI to provide an immersive experience for both real estate agents and homebuyers. Users explore homes virtually, with AI insights and real-time agent collaboration via WebSockets.',
    role: 'Full-stack engineer',
    timeline: '2024',
    tech: ['Next.js', 'Tailwind', 'FastAPI', 'Node.js', 'AR-VR', 'Socket.IO', 'Pannellum', 'MongoDB', 'Three.js'],
    features: ['Immersive 3D Tours', 'AI-Powered Recommendations', 'Real-Time Collaboration', 'Advanced Analytics Dashboard'],
    metrics: [['rooms/listing', '12'], ['fov', '360°'], ['fps', '60']],
    link: 'https://realestate360.vercel.app/',
    github: 'https://github.com/Archit1706/RealEstate360',
  },
  {
    slug: 'ascend-ai',
    title: 'Ascend AI',
    subtitle: 'AI-powered interview preparation coach',
    category: 'AI/ML',
    year: '2024',
    featured: true,
    widget: 'tonePitch',
    desc: 'Interview preparation platform with cutting-edge AI analysis: real-time tone and pitch feedback, facial expression recognition (Xception + OpenCV), and precise video mock interview reviews. Uses LIBROSA for vocal feature extraction and a 1D-CNN trained on RAVDESS, TESS, SAVEE, and CREMA-D.',
    role: 'AI/ML engineer · Co-author',
    timeline: '2024',
    tech: ['Next.js', 'Tailwind', 'Llama C++', 'FastAPI', 'Librosa', 'Transformers', 'OpenCV', 'MongoDB', 'Whisper'],
    features: ['AI-Powered Interview Analysis', 'Real-Time Tone and Pitch Feedback', 'Facial Expression Recognition', 'Comprehensive Video Mock Interview Reviews'],
    metrics: [['emotion classes', '7'], ['f1 score', '0.87'], ['datasets', '4']],
    link: 'https://ascend-ai-mpr.vercel.app/',
    github: 'https://github.com/Archit1706/AscendAI',
  },
  {
    slug: 'phishfence',
    title: 'PhishFence',
    subtitle: 'Real-time phishing domain detection',
    category: 'AI/ML · Security',
    year: '2024',
    featured: true,
    widget: 'urlScanner',
    desc: 'AI/ML-powered solution that automatically detects and blocks phishing domains among newly registered websites. Integrates WHOIS data, real-time URL fetching, image comparison, and typosquatting checks via LightGBM. A user-friendly chatbot assists end users with informed decisions.',
    role: 'ML engineer',
    timeline: '2024',
    tech: ['Next.js', 'Tailwind', 'Selenium', 'FastAPI', 'WhoisDB', 'LightGBM', 'OpenCV', 'OpenAI'],
    features: ['Real-Time Phishing Detection', 'Comprehensive Threat Analysis', 'User-Friendly Interface', 'AI-Powered Chatbot Assistance'],
    metrics: [['features', '32'], ['precision', '0.94'], ['avg scan', '1.1s']],
    link: 'https://phishfence.vercel.app/',
    github: 'https://github.com/Archit1706/PhishFence',
  },
  {
    slug: 'fitsphere',
    title: 'FitSphere',
    subtitle: 'Pose-estimation fitness coach',
    category: 'AI/ML · CV',
    year: '2023',
    widget: 'pose',
    desc: 'Pose estimation system leveraging Computer Vision and ML for sports and fitness — automated exercise recognition, accurate rep/set counting, progress tracking, and a real-time form-warning system.',
    role: 'CV engineer',
    timeline: '2023',
    tech: ['React.js', 'Tailwind', 'OpenCV', 'FastAPI', 'MongoDB', 'PoseNet', 'OpenPose'],
    features: ['Automated Exercise Recognition', 'Accurate Rep and Set Counting', 'Progress Tracking', 'Exercise Recommendations', 'Warning System'],
    metrics: [['keypoints', '17'], ['exercises', '12'], ['fps', '30']],
    link: 'https://fitsphere.vercel.app/',
    github: 'https://github.com/Archit1706/FitSphere',
  },
  {
    slug: 'swarbhaav',
    title: 'SwarBhaav',
    subtitle: 'Call-centre sentiment & coaching dashboard',
    category: 'AI/ML · NLP',
    year: '2023',
    widget: 'audioSent',
    desc: 'Dual-dashboard call-centre solution for rookies and managers. Chat summarization with sentiment scores and keywords, audio sentiment analysis with seven-emotion classification via librosa, and a robust MongoDB-backed reporting system.',
    role: 'Full-stack + ML',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'Node.js', 'FastAPI', 'Librosa', 'Transformers', 'OpenAI'],
    features: ['Dual Dashboards', 'Chat Analysis', 'Audio Sentiment Analysis', 'Comprehensive Reporting System'],
    metrics: [['emotions', '7'], ['avg call', '4.2 min'], ['accuracy', '88%']],
    link: 'https://swarbhaav.vercel.app/',
    github: 'https://github.com/Archit1706/SwarBhaav',
  },
  {
    slug: 'attire-ai',
    title: 'Attire AI',
    subtitle: 'Gen-AI fashion outfit recommender',
    category: 'AI/ML · Gen AI',
    year: '2023',
    widget: 'attireAi',
    desc: 'Gen-AI fashion companion. Personalized outfit recommendations through conversational interactions — analyzes style preferences, past purchases, and social media trends to curate cohesive outfits for Flipkart shoppers.',
    role: 'AI engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'Flask', 'LangChain', 'LLama', 'NLTK'],
    features: ['Personalized Outfit Recommendations', 'Conversational Interface', 'Style Analysis', 'Trend Integration', 'Google Search Integration'],
    metrics: [['styles', '24'], ['fit-score', '0.81']],
    link: 'https://attire-ai.vercel.app',
    github: 'https://github.com/Archit1706/Attire-AI',
  },
  {
    slug: 'bid-bazaar',
    title: 'Bid Bazaar',
    subtitle: 'Real-time online auction platform',
    category: 'Full Stack',
    year: '2023',
    widget: 'auction',
    desc: 'Online auction platform supporting cars, real estate, and government contracts. Live bidding via Socket.io, in-room chat, and reverse-auction mode for government tenders.',
    role: 'Full-stack engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'Node.js', 'Express', 'MongoDB', 'Socket.io', 'Cloudinary'],
    features: ['Real-Time Bidding', 'Diverse Auction Categories', 'User Chat Feature', 'Reverse Auction for Government Contracts', 'Live Bidding'],
    metrics: [['categories', '6'], ['avg bid latency', '<60ms']],
    link: 'https://bid-bazaar.vercel.app/',
    github: 'https://github.com/Archit1706/TIAA-Hackathon',
  },
  {
    slug: 'coupon-vault',
    title: 'Coupon Vault',
    subtitle: 'Headless promotion engine',
    category: 'Full Stack',
    year: '2023',
    widget: 'couponVault',
    desc: 'Headless promotion engine for merchants — dynamic and static coupon code generation with full attribute customization. Flexible, scalable, integrates into any web/app platform.',
    role: 'Full-stack engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'Node.js', 'Express', 'MongoDB'],
    features: ['Dynamic and Static Coupon Generation', 'Customizable Coupon Attributes', 'Flexible Integration', 'Usage Limits and Expiration Settings', 'SKUs and Categories'],
    metrics: [['rules engine', '14 ops']],
    link: 'https://coupon-vault.vercel.app/',
    github: 'https://github.com/Archit1706/Coupon-Vault',
  },
  {
    slug: 'reflections',
    title: 'Reflections Blogs',
    subtitle: 'AI-augmented blogging platform',
    category: 'Web · AI',
    year: '2023',
    widget: 'reflections',
    desc: 'Blogging platform empowering individuals to share unique stories. ML-assisted writing, personalized profiles, and content discovery powered by OpenAI.',
    role: 'Full-stack engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'ML Models', 'Python', 'MongoDB', 'OpenAI'],
    features: ['User-Friendly Editor', 'Personalized Profiles', 'Content Discovery', 'AI-Powered Writing Assistance', 'Community Engagement'],
    link: 'https://reflections-blog.vercel.app/',
    github: 'https://github.com/Archit1706/Reflections-Blogs',
  },
  {
    slug: 'power-up',
    title: 'Power Up',
    subtitle: 'Wear OS health & diet companion',
    category: 'Full Stack · Wearables',
    year: '2023',
    widget: 'powerUp',
    desc: 'Health monitoring and diet tracking app integrating with Wear OS smartwatches via Google Fitness. Tracks weight, steps, calories, and sets goals with AI chatbot support.',
    role: 'Full-stack engineer',
    timeline: '2023',
    tech: ['React.js', 'Tailwind', 'Node.js', 'Express', 'MongoDB'],
    features: ['Wearable Device Integration', 'Real-Time Health Monitoring', 'Personalized Diet Plans', 'AI Chatbot Support'],
    link: 'https://powerup.sidd065.repl.co/',
    github: 'https://github.com/Archit1706/PowerUp',
  },
  {
    slug: 'edusys',
    title: 'EduSys',
    subtitle: 'Outcome-Based Education automation',
    category: 'Full Stack',
    year: '2022',
    widget: 'edusys',
    desc: 'Web app mapping COs, POs, and PSOs of a course to corresponding outcomes — automating the entire flow of OBE for college faculty.',
    role: 'Full-stack engineer',
    timeline: '2022',
    tech: ['React.js', 'Tailwind', 'Node.js', 'Express', 'MongoDB'],
    features: ['Course Outcome Mapping', 'Automated OBE Workflow', 'Faculty Dashboard', 'Performance Analytics'],
    link: 'https://edusys-tsec.netlify.app/',
    github: 'https://github.com/Archit1706/EduSys-Frontend',
  },
  {
    slug: 'social-vision',
    title: 'Social Vision',
    subtitle: 'Coordinated-inauthentic-behavior detector',
    category: 'AI/ML · NLP',
    year: '2023',
    widget: 'network',
    desc: 'System detecting coordinated inauthentic behavior on social platforms. Network visualization, agenda detection via keyword extraction, propaganda multi-class classification, and fake-news identification via sentiment analysis.',
    role: 'ML engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'MongoDB', 'Python', 'ML Models', 'FastAPI'],
    features: ['Network Visualization', 'Agenda Detection', 'Propaganda Classification', 'Fake News Identification', 'Keyword Extraction'],
    link: 'https://social-vision.vercel.app/',
    github: 'https://github.com/Archit1706/SocialVision',
  },
  {
    slug: 'first-paper',
    title: 'First Paper',
    subtitle: 'Research-paper topic recommender',
    category: 'AI/ML',
    year: '2023',
    widget: 'firstPaper',
    desc: 'Helps students, professors, and researchers gather existing research and discover new topics through ML-driven suggestions over the ArXiv dataset.',
    role: 'ML engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'MongoDB', 'Python', 'ArXiv Dataset'],
    features: ['Research Paper Suggestions', 'Domain and Topic Recommendations', 'Existing Work Compilation', 'User-Friendly Interface'],
    link: 'https://first-paper.vercel.app/',
    github: 'https://github.com/Archit1706/First-Paper',
  },
  {
    slug: 'the-one-finder',
    title: 'The One Finder',
    subtitle: 'AI-driven dating with E2E chat',
    category: 'Full Stack · AI',
    year: '2023',
    widget: 'oneFinder',
    desc: 'AI-ML-powered dating app — profile scoring, sentiment analysis on bios, end-to-end encrypted chat, swipe-based matching, Stripe-backed pro tier.',
    role: 'Full-stack engineer',
    timeline: '2023',
    tech: ['Next.js', 'Tailwind', 'MongoDB', 'Firebase', 'Python', 'FastAPI'],
    features: ['Profile Scoring System', 'Sentiment Analysis', 'End-to-End Encrypted Chat', 'Swipe-Based Matching', 'Stripe Payment Integration'],
    link: 'https://the-one-finder.vercel.app/',
    github: 'https://github.com/Archit1706/The-One-Finder',
  },
  {
    slug: 'home-ginie',
    title: 'Home Ginie',
    subtitle: 'US house-price prediction',
    category: 'AI/ML',
    year: '2022',
    widget: 'homeGinie',
    desc: 'Predicts US home prices from average income, house age, room count, and population using a tuned linear regression model exposed via FastAPI.',
    role: 'ML engineer',
    timeline: '2022',
    tech: ['Next.js', 'Tailwind', 'Python', 'Linear Regression', 'FastAPI'],
    features: ['Accurate Price Prediction', 'User-Friendly Interface', 'Interactive House Gallery', 'Advanced Algorithm'],
    link: 'https://home-ginie.vercel.app/',
    github: 'https://github.com/Archit1706/Home-Ginie',
  },
  {
    slug: 'moviescape',
    title: 'Moviescape',
    subtitle: 'TMDB-powered movie discovery',
    category: 'Web',
    year: '2022',
    widget: 'moviescape',
    desc: 'Web app displaying the latest movies and TV shows with ratings, release dates, genres, and overviews via the TMDB API.',
    role: 'Frontend engineer',
    timeline: '2022',
    tech: ['React.js', 'Tailwind', 'TMDB API'],
    features: ['Responsive design', 'Real-time search and filtering', 'User-friendly interface'],
    link: 'https://moviescape.netlify.app/',
    github: 'https://github.com/Archit1706/Movie-App',
  },
  {
    slug: 'emoji-nation',
    title: 'Emoji Nation',
    subtitle: 'Emoji search engine',
    category: 'Web',
    year: '2022',
    widget: 'emojiNation',
    desc: 'Searchable emoji directory pulling from the emoji API and surfacing meaning on hover, in a dense responsive grid.',
    role: 'Frontend engineer',
    timeline: '2022',
    tech: ['React.js', 'CSS', 'API'],
    features: ['Search Functionality', 'Responsive Design', 'Emoji Categories'],
    link: 'https://emoji-nation.netlify.app/',
    github: 'https://github.com/Archit1706/Emoji-Nation',
  },
  {
    slug: 'healthy-me',
    title: 'Healthy Me!',
    subtitle: 'Daily calorie + water tracker',
    category: 'Full Stack',
    year: '2022',
    widget: 'healthyMe',
    desc: 'Tracks daily calorie intake by logging breakfast, lunch, dinner and water intake, surfacing totals and trends.',
    role: 'Full-stack engineer',
    timeline: '2022',
    tech: ['React.js', 'Tailwind', 'Node.js', 'MongoDB', 'Food API'],
    features: ['Calorie Tracking', 'Water Intake Monitoring', 'Food Database Integration', 'User Authentication'],
    github: 'https://github.com/Archit1706/Codeissance_22_Keyboard-Interrupt',
  },
  {
    slug: 'proctor-it',
    title: 'Proctor It!',
    subtitle: 'Virtual exam invigilator',
    category: 'AI/ML · CV',
    year: '2022',
    widget: 'proctorIt',
    desc: 'Detects faces before exam start and tracks eye movement during the exam using OpenCV and Tkinter.',
    role: 'CV engineer',
    timeline: '2022',
    tech: ['Python', 'OpenCV', 'Tkinter'],
    features: ['Face Detection', 'Eye Movement Tracking', 'Real-Time Monitoring', 'User-Friendly Interface'],
    github: 'https://github.com/Archit1706/PROCTOR_IT-A-Virtual-Invigilator',
  },
  {
    slug: 'weather-today',
    title: 'Weather Today',
    subtitle: 'OpenWeather city forecast',
    category: 'Web',
    year: '2021',
    widget: 'weatherToday',
    desc: 'Web app surfacing current weather for any city via OpenWeather — temperature, humidity, wind speed.',
    role: 'Frontend engineer',
    timeline: '2021',
    tech: ['HTML', 'CSS', 'Node.js', 'API'],
    features: ['Search by City Name', 'Current Weather Display', 'Temperature, Humidity, Wind Speed', 'Responsive Design'],
    link: 'https://weather-today.architrathod1.repl.co/',
    github: 'https://github.com/Archit1706/Weather-Today',
  },
  {
    slug: 'random-quote-generator',
    title: 'Random Quote Generator',
    subtitle: 'Color-shifting quote machine',
    category: 'Web',
    year: '2021',
    widget: 'randomQuote',
    desc: 'Pulls quotes from an API into a card, generates a new quote with a random color scheme, and tweets it.',
    role: 'Frontend engineer',
    timeline: '2021',
    tech: ['HTML', 'CSS', 'JS', 'API'],
    features: ['Random Quote Generation', 'Dynamic Color Scheme', 'Tweet Integration', 'Responsive Design'],
    link: 'https://archit1706.github.io/Random-Quote-Generator/',
    github: 'https://github.com/Archit1706/Random-Quote-Generator',
  },
];

export const PROJECT_BY_SLUG = Object.fromEntries(PROJECTS.map((p) => [p.slug, p]));
